"""
Review Model

This module defines the SQLAlchemy ORM model responsible
for storing code review results generated by the Advanced
GitHub Code Reviewer platform.

Purpose
-------
The Review table stores the outcome of a code review
execution performed on a GitHub Pull Request.

Each review represents a single execution of the
code review workflow.

This design allows the platform to support:

• Multiple review attempts
• Agent reflection loops
• Human-in-the-loop approvals
• Historical review tracking
• Debugging of review pipelines

Relationships
-------------
PullRequest
    └── Review
            └── ReviewStep

Table Name
----------
reviews

Example Record
--------------
id: 1
pull_request_id: 4
reviewer: "ai"
status: "completed"
verdict: "changes_requested"
summary: "Several lint issues detected."

Usage
-----
    from app.db.models.review import Review
"""

import sys

from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.db.base import Base
from app.core.logger import get_logger
from app.core.exceptions import CustomException


logger = get_logger(__name__)


class Review(Base):
    """
    SQLAlchemy ORM model representing a code review
    executed on a pull request.

    Attributes
    ----------
    id : int
        Primary key identifier for the review.

    pull_request_id : int
        Foreign key referencing the associated pull request.

    reviewer : str
        Type of reviewer that performed the review.

        Possible values:
        - ai
        - human
        - system

    status : str
        Current status of the review workflow.

        Possible values:
        - pending
        - running
        - completed
        - failed

    verdict : str
        Final decision of the review.

        Possible values:
        - approved
        - changes_requested
        - comment_only

    summary : str
        High-level summary of the review results.

    created_at : datetime
        Timestamp when the review started.

    updated_at : datetime
        Timestamp when the review was last updated.
    """

    try:

        __tablename__ = "reviews"

        id = Column(Integer, primary_key=True, index=True)

        pull_request_id = Column(
            Integer,
            ForeignKey("pull_requests.id"),
            nullable=False,
            index=True
        )

        reviewer = Column(
            String(50),
            default="ai",
            nullable=False
        )

        status = Column(
            String(50),
            default="pending",
            nullable=False
        )

        verdict = Column(
            String(50),
            nullable=True
        )

        summary = Column(
            Text,
            nullable=True
        )

        created_at = Column(
            DateTime(timezone=True),
            server_default=func.now(),
            nullable=False
        )

        updated_at = Column(
            DateTime(timezone=True),
            onupdate=func.now()
        )

        # Relationship → Pull Request
        pull_request = relationship(
            "PullRequest",
            backref="reviews"
        )

        # Relationship → Review Steps
        steps = relationship(
            "ReviewStep",
            backref="review",
            cascade="all, delete-orphan"
        )

        logger.info("Review model initialized successfully")

    except Exception as e:
        logger.error("Error while defining Review model")
        raise CustomException(e, sys)

    def __repr__(self):
        """
        Return readable string representation
        useful for debugging and logs.
        """
        return f"<Review(pr_id={self.pull_request_id}, status={self.status})>"