"""
ReviewStep Model

This module defines the SQLAlchemy ORM model responsible for
storing individual execution steps performed during a code
review workflow.

Purpose
-------
The ReviewStep table records granular execution details for
each step executed by the automated code review system.

Instead of storing only the final review result, this table
captures the entire execution trace of the agent workflow.

Each review can consist of multiple steps such as:

• Fetch Pull Request diff
• Run linters
• Execute unit tests
• Perform security scan
• Run AI code review
• Execute reflection loop
• Generate final verdict

This design enables:

• Full observability of the agent workflow
• Debugging failed review pipelines
• Execution trace auditing
• Human-in-the-loop review inspection
• Agent reflection and retries

Relationships
-------------
PullRequest
    └── Review
            └── ReviewStep

Table Name
----------
review_steps

Example Record
--------------
id: 1
review_id: 5
step_name: "run_linter"
status: "completed"
input_data: "lint configuration"
output_data: "3 warnings detected"
logs: "flake8 completed successfully"

Usage
-----
    from app.db.models.review_step import ReviewStep
"""

import sys
from datetime import datetime

from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship

from app.db.base import Base
from app.core.logger import get_logger
from app.core.exceptions import CustomException


logger = get_logger(__name__)


class ReviewStep(Base):
    """
    SQLAlchemy ORM model representing a single execution
    step in the code review workflow.

    Attributes
    ----------
    id : int
        Primary key identifier for the review step.

    review_id : int
        Foreign key referencing the parent review.

    step_name : str
        Name of the workflow step.

        Examples:
        - fetch_pr_diff
        - run_linter
        - run_tests
        - security_scan
        - ai_review
        - reflection_step

    status : str
        Execution status of the step.

        Possible values:
        - pending
        - running
        - completed
        - failed

    input_data : str
        Input provided to the step (JSON/text format).

    output_data : str
        Output produced by the step (JSON/text format).

    logs : str
        Execution logs generated by the step.

    created_at : datetime
        Timestamp when the step execution was created.
    """

    try:
        __tablename__ = "review_steps"

        id = Column(Integer, primary_key=True, index=True)

        review_id = Column(
            Integer,
            ForeignKey("reviews.id"),
            nullable=False,
            index=True
        )

        step_name = Column(
            String(100),
            nullable=False
        )

        status = Column(
            String(50),
            default="pending",
            nullable=False
        )

        input_data = Column(
            Text,
            nullable=True
        )

        output_data = Column(
            Text,
            nullable=True
        )

        logs = Column(
            Text,
            nullable=True
        )

        created_at = Column(
            DateTime,
            default=datetime.utcnow,
            nullable=False
        )

        # Relationship to Review
        review = relationship(
            "Review",
            backref="steps"
        )

        logger.info("ReviewStep model initialized successfully")

    except Exception as e:
        logger.error("Error while defining ReviewStep model")
        raise CustomException(e, sys)

    def __repr__(self):
        """
        Return readable string representation of the review step.
        Useful for debugging and logging.
        """
        return f"<ReviewStep(step={self.step_name}, status={self.status})>"