"""
app/api/routes/chat.py

Chat API Routes
----------------
REST endpoints for managing conversation threads tied to PR reviews.

Endpoints:
    POST   /chat/{thread_id}/messages   — send a message, get AI response
    GET    /chat/{thread_id}/messages   — fetch all messages in a thread
    DELETE /chat/{thread_id}            — delete all messages in a thread

All routes delegate to chat_service.py — no business logic lives here.

Thread ID convention:
    Use the PR identifier as the thread_id for natural association:
    e.g. "Basant19-my-repo-7"  (owner-repo-pr_number)

    Any string works — the thread is created automatically on first message.

Message roles:
    "user"   — message sent by the developer
    "ai"     — response generated by the AI
    "system" — system-level context messages
"""

import sys
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from fastapi import status as http_status
from pydantic import BaseModel, ConfigDict
from sqlalchemy.orm import Session

from app.api.deps import get_db
from app.core.exceptions import CustomException
from app.core.logger import get_logger
from app.services.chat_service import ChatService

logger = get_logger(__name__)

router = APIRouter(prefix="/chat", tags=["chat"])


# ── Request / Response schemas ────────────────────────────────────────────────

class SendMessageRequest(BaseModel):
    content: str
    role:    str = "user"


class MessageResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id:         int
    thread_id:  int
    role:       str
    content:    str
    created_at: Optional[str] = None


class ThreadMessagesResponse(BaseModel):
    thread_id:     str
    message_count: int
    messages:      list[MessageResponse]


class DeleteThreadResponse(BaseModel):
    thread_id: str
    deleted:   bool
    message:   str


# ── Helper ────────────────────────────────────────────────────────────────────

def _handle_service_error(e: Exception, context: str) -> None:
    """
    Converts CustomException to HTTP responses.
    "not found" → 404, everything else → 500.
    """
    message = str(e).lower()
    if "not found" in message:
        raise HTTPException(
            status_code=http_status.HTTP_404_NOT_FOUND,
            detail=str(e),
        )
    logger.error(f"[chat_route] {context}: {e}")
    raise HTTPException(
        status_code=http_status.HTTP_500_INTERNAL_SERVER_ERROR,
        detail=f"Internal error during {context}",
    )


# ── Routes ────────────────────────────────────────────────────────────────────

@router.post(
    "/{thread_id}/messages",
    status_code=http_status.HTTP_201_CREATED,
    response_model=MessageResponse,
    summary="Send a message in a thread",
)
def send_message(
    thread_id: str,
    request:   SendMessageRequest,
    db:        Session = Depends(get_db),
) -> MessageResponse:
    """
    Creates a new message in the given thread.

    The thread is created automatically if it does not exist yet.
    Returns the persisted message object.

    Args:
        thread_id: String identifier for the conversation thread.
                   Convention: "{owner}-{repo}-{pr_number}"
        request:   Message content and role (default: "user")
    """
    logger.info(
        f"[chat_route] Send message — thread_id={thread_id}, "
        f"role={request.role}"
    )

    try:
        chat_service = ChatService(db)
        message = chat_service.create_message(
            thread_id=thread_id,
            role=request.role,
            content=request.content,
        )

        return MessageResponse(
            id=message.id,
            thread_id=message.thread_id,
            role=message.role,
            content=message.content,
            created_at=str(message.created_at) if message.created_at else None,
        )

    except CustomException as e:
        _handle_service_error(e, "send_message")


@router.get(
    "/{thread_id}/messages",
    status_code=http_status.HTTP_200_OK,
    response_model=ThreadMessagesResponse,
    summary="Get all messages in a thread",
)
def get_messages(
    thread_id: str,
    db:        Session = Depends(get_db),
) -> ThreadMessagesResponse:
    """
    Returns all messages in a thread ordered by creation time (oldest first).

    Returns an empty messages list if the thread exists but has no messages.
    Returns 404 if the thread does not exist at all.

    Args:
        thread_id: String identifier for the conversation thread
    """
    logger.info(f"[chat_route] Get messages — thread_id={thread_id}")

    try:
        chat_service = ChatService(db)
        messages     = chat_service.get_messages(thread_id=thread_id)

        return ThreadMessagesResponse(
            thread_id=thread_id,
            message_count=len(messages),
            messages=[
                MessageResponse(
                    id=m.id,
                    thread_id=m.thread_id,
                    role=m.role,
                    content=m.content,
                    created_at=str(m.created_at) if m.created_at else None,
                )
                for m in messages
            ],
        )

    except CustomException as e:
        _handle_service_error(e, "get_messages")


@router.delete(
    "/{thread_id}",
    status_code=http_status.HTTP_200_OK,
    response_model=DeleteThreadResponse,
    summary="Delete all messages in a thread",
)
def delete_thread(
    thread_id: str,
    db:        Session = Depends(get_db),
) -> DeleteThreadResponse:
    """
    Deletes all messages belonging to a thread.

    The thread record itself may be retained depending on ChatService
    implementation — only messages are guaranteed to be removed.

    Returns 404 if the thread does not exist.

    Args:
        thread_id: String identifier for the conversation thread
    """
    logger.info(f"[chat_route] Delete thread — thread_id={thread_id}")

    try:
        chat_service = ChatService(db)
        chat_service.delete_thread(thread_id=thread_id)

        return DeleteThreadResponse(
            thread_id=thread_id,
            deleted=True,
            message=f"Thread '{thread_id}' deleted successfully",
        )

    except CustomException as e:
        _handle_service_error(e, "delete_thread")