"""
app/main.py

FastAPI Application Entry Point — P4 Production Version
--------------------------------------------------------
Creates the FastAPI application, registers all routers, runs database
initialization on startup, and provides global exception handling.

Run
---
    uvicorn app.main:app --host 0.0.0.0 --port 8000

API Documentation (auto-generated by FastAPI)
---------------------------------------------
    http://localhost:8000/docs      ← Swagger UI
    http://localhost:8000/redoc     ← ReDoc

Registered Routers
------------------
    /webhook            ← GitHub webhook events (P1)
    /reviews            ← Review CRUD + trigger + HITL decision (P1/P3)
    /chat               ← Thread-based messaging stub (P1, fully wired P5)
    /reviews (HITL)     ← approve / reject / status endpoints (P3)
    /repos              ← Repository indexing for ChromaDB RAG (P4)

P4 New Endpoints
----------------
    POST   /repos/index                  — clone + chunk + embed + store
    GET    /repos/{owner}/{repo}/status  — check if repo is indexed
    DELETE /repos/{owner}/{repo}/index   — clear repo chunks from ChromaDB

Route Conflict Note
-------------------
GET /reviews/ is defined here (not in review.py) to avoid a FastAPI
route ordering conflict. Routes registered in review.py start with
/reviews/{param} which would shadow a plain /reviews/ path if defined
there. Defining it here after include_router() ensures correct ordering.

Startup Lifecycle
-----------------
on_startup() runs once when uvicorn starts:
    1. Creates all SQLAlchemy tables if they do not exist (create_all)
    2. Logs environment, DB, and LangSmith config for verification
    Failure here raises RuntimeError — server refuses to start
    with a clear log message rather than silently serving broken requests.

Global Exception Handlers
--------------------------
CustomException  → HTTP 500 with message from the exception
Exception        → HTTP 500 with generic "Internal Server Error"
Both log the error with the request path for traceability.
HTTPException is NOT intercepted — FastAPI handles it natively.

Request Logging Middleware
--------------------------
Every request is logged on entry and exit with method, path,
status code, and duration_ms. Exceptions in the request pipeline
are re-raised after logging so FastAPI's error handling still fires.
"""

import time
import traceback

from fastapi import FastAPI, Depends, Request, HTTPException
from fastapi.responses import JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.routes import webhook, review, chat
from app.api.routes.hitl import router as hitl_router
from app.api.routes.repos import router as repos_router
from app.core.config import settings
from app.core.exceptions import CustomException
from app.core.logger import get_logger
from app.db.base import Base
from app.db.session import engine
from app.api.deps import get_db
from app.services.review_service import list_all_reviews

logger = get_logger(__name__)


# ── Application Instance ──────────────────────────────────────────────────────

app = FastAPI(
    title="Advanced GitHub Code Reviewer",
    description=(
        "Agentic AI platform that automatically reviews GitHub Pull Requests "
        "using LangGraph, Gemini 2.5 Flash Lite, PostgreSQL, Docker sandbox, "
        "and ChromaDB RAG.\n\n"
        "**HITL Flow:**\n"
        "1. `POST /reviews/trigger` — run AI review, pauses at HITL gate\n"
        "2. `POST /reviews/id/{id}/decision` — approve or reject\n"
        "3. Review completes, GitHub comment posted (if approved)\n\n"
        "**RAG Flow (P4):**\n"
        "1. `POST /repos/index` — index a repository into ChromaDB\n"
        "2. Trigger reviews normally — context injected automatically"
    ),
    version="4.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)


# ── Request Logging Middleware ────────────────────────────────────────────────

@app.middleware("http")
async def log_requests(request: Request, call_next):
    """
    Log every incoming request and outgoing response with timing.

    Logs method, path, status code, and duration_ms for every request.
    On unhandled exception, logs the crash details and re-raises so
    FastAPI's exception handlers still fire correctly.

    Parameters
    ----------
    request : Request
    call_next : Callable
        Next middleware or route handler in the chain.
    """
    start_time = time.time()

    logger.info(
        "[REQUEST] %s %s — client=%s",
        request.method,
        request.url.path,
        request.client.host if request.client else "unknown",
    )

    try:
        response = await call_next(request)
        duration_ms = round((time.time() - start_time) * 1000, 2)

        logger.info(
            "[RESPONSE] %s %s → %d (%sms)",
            request.method,
            request.url.path,
            response.status_code,
            duration_ms,
        )

        return response

    except Exception as e:
        duration_ms = round((time.time() - start_time) * 1000, 2)

        logger.exception(
            "[CRASH] %s %s failed after %sms — error=%s",
            request.method,
            request.url.path,
            duration_ms,
            str(e),
        )
        raise


# ── Startup ───────────────────────────────────────────────────────────────────

@app.on_event("startup")
async def on_startup() -> None:
    """
    Application startup handler — runs once when uvicorn starts.

    Steps
    -----
    1. Create all SQLAlchemy ORM tables if they do not exist.
       Uses create_all() — safe to call on existing databases.
    2. Log environment configuration for verification.

    Failure Behaviour
    -----------------
    Any exception here raises RuntimeError which causes uvicorn to
    exit immediately with a clear error message. This is intentional —
    a server that cannot connect to its database should not start.

    Raises
    ------
    RuntimeError
        If database initialization fails.
    """
    logger.info(
        "[startup] Starting Advanced GitHub Code Reviewer P4 — "
        "version=4.0.0"
    )

    try:
        logger.info("[startup] Initializing database tables")

        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)

        logger.info("[startup] Database tables ready")

        logger.info(
            "[startup] Configuration — "
            "environment=%s db=%s langsmith_tracing=%s",
            settings.ENVIRONMENT,
            bool(settings.DATABASE_URL),
            settings.LANGSMITH_TRACING,
        )

        logger.info("[startup] Application startup complete")

    except Exception as e:
        logger.exception("[startup] Database initialization failed — %s", str(e))
        raise RuntimeError(
            f"Application startup failed: {e}"
        ) from e


# ── Global Exception Handlers ─────────────────────────────────────────────────

@app.exception_handler(CustomException)
async def custom_exception_handler(
    request: Request,
    exc: CustomException,
) -> JSONResponse:
    """
    Convert unhandled CustomException to HTTP 500 JSON response.

    CustomExceptions that escape route handlers and service functions
    are caught here as a last resort. Routes should catch CustomException
    and convert to HTTPException with appropriate status codes before
    this handler fires.

    Parameters
    ----------
    request : Request
    exc : CustomException

    Returns
    -------
    JSONResponse
        HTTP 500 with exception message in detail field.
    """
    logger.error(
        "[exception_handler] CustomException on %s — %s",
        request.url.path,
        str(exc),
    )
    return JSONResponse(
        status_code=500,
        content={"detail": str(exc)},
    )


@app.exception_handler(Exception)
async def global_exception_handler(
    request: Request,
    exc: Exception,
) -> JSONResponse:
    """
    Catch-all handler for any unhandled exception.

    Fires for exceptions that are not HTTPException and not CustomException.
    Logs the full traceback at DEBUG level for development and returns
    a generic error message to the client.

    Parameters
    ----------
    request : Request
    exc : Exception

    Returns
    -------
    JSONResponse
        HTTP 500 with generic error message.
    """
    logger.error(
        "[exception_handler] Unhandled exception on %s — type=%s message=%s",
        request.url.path,
        type(exc).__name__,
        str(exc),
    )
    logger.debug("[exception_handler] Traceback:\n%s", traceback.format_exc())

    return JSONResponse(
        status_code=500,
        content={"detail": "Internal Server Error"},
    )


# ── Router Registration ───────────────────────────────────────────────────────

app.include_router(webhook.router)
app.include_router(review.router)
app.include_router(chat.router)
app.include_router(hitl_router)
app.include_router(repos_router)        # ← P4: /repos/index, /repos/status

logger.info(
    "[startup] Routers registered — "
    "/webhook, /reviews, /chat, /reviews (HITL), /repos (P4 RAG)"
)


# ── Dashboard Endpoint ────────────────────────────────────────────────────────
# Defined here (not in review.py) to avoid route ordering conflict.
# review.py defines /reviews/{param} paths which would shadow /reviews/
# if defined there. Registering after include_router() ensures /reviews/
# is matched before parameterized paths.

@app.get(
    "/reviews/",
    tags=["reviews"],
    summary="List all reviews (dashboard)",
    description=(
        "Returns all reviews across all repositories, newest first. "
        "Used by the Streamlit admin dashboard to populate the PR list."
    ),
)
async def get_all_reviews(
    db: AsyncSession = Depends(get_db),
):
    """
    List all reviews across all repositories.

    Returns enriched dicts with PR number, repo name, PR title, author,
    branch, and thread_id for the Streamlit dashboard. Newest first.
    """
    logger.info("[get_all_reviews] Dashboard request — fetching all reviews")

    try:
        reviews = await list_all_reviews(db)
        logger.info(
            "[get_all_reviews] Returning %d review(s)", len(reviews),
        )
        return reviews

    except CustomException as e:
        logger.error("[get_all_reviews] Service error — %s", str(e))
        raise HTTPException(status_code=500, detail=str(e))

    except Exception as e:
        logger.exception("[get_all_reviews] Unexpected error")
        raise HTTPException(status_code=500, detail="Internal server error")


# ── Health Check ──────────────────────────────────────────────────────────────

@app.get(
    "/health",
    tags=["health"],
    summary="Health check",
    description=(
        "Returns server status and version. "
        "Used by load balancers, uptime monitors, and Docker health checks."
    ),
)
async def health_check() -> dict:
    """
    Return server health status.

    Does not check database connectivity — add a SELECT 1 query in P6
    for a deep health check that verifies DB connection is alive.
    """
    return {
        "status":      "ok",
        "version":     "4.0.0",
        "phase":       "P4",
        "environment": settings.ENVIRONMENT,
    }