"""
app/graph/state.py

ReviewState — LangGraph State Definition
-----------------------------------------
TypedDict that defines the complete state object passed between nodes.

LangGraph passes the full state to every node. Each node returns a
PARTIAL dict — LangGraph merges the returned keys into the existing state.
Keys not returned by a node are left unchanged.

P1 fields (unchanged — 28 tests passing):
    owner, repo, pr_number, thread_id
    metadata, files, diff
    issues, suggestions, repo_context
    reflection_count
    verdict, summary

P2 fields (new — default to None / False so P1 tests still pass):
    lint_result        — SandboxResult from lint_node (ruff check)
    lint_passed        — bool shortcut so should_refactor() reads cleanly
    patch              — unified diff patch generated by refactor_node
    validation_result  — SandboxResult from validator_node (ruff + pytest)

TYPE NOTE on SandboxResult
--------------------------
SandboxResult is imported with TYPE_CHECKING only to avoid a circular
import at runtime. nodes.py imports from state.py AND from sandbox.
Using Optional[Any] at runtime keeps the TypedDict lightweight.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Optional
from typing_extensions import TypedDict

if TYPE_CHECKING:
    from app.sandbox.docker_runner import SandboxResult


class ReviewState(TypedDict, total=False):
    """
    Complete state object for the LangGraph review workflow.

    total=False means all keys are optional at the TypedDict level.
    build_initial_state() always provides sensible defaults so nodes
    can safely access any key without a KeyError.
    """

    # ── Identity ──────────────────────────────────────────────────────────
    owner      : str    # GitHub repo owner login
    repo       : str    # GitHub repo name
    pr_number  : int    # Pull request number
    thread_id  : str    # MemorySaver checkpoint key: "{owner}-{repo}-{pr}"

    # ── GitHub data (set by fetch_diff_node) ──────────────────────────────
    metadata   : dict        # title, author, base_branch, head_branch
    files      : list[str]   # list of changed file paths
    diff       : str         # unified diff text from GitHub API

    # ── Review findings (set by analyze_code_node / reflect_node) ─────────
    issues      : list[str]  # code issues found — drives verdict
    suggestions : list[str]  # improvement suggestions
    repo_context: str        # ChromaDB context chunks used in analysis

    # ── Reflection counter (used by both P1 and P2 loop controls) ─────────
    reflection_count : int   # incremented by reflect_node / refactor_node

    # ── P2: Sandbox results ───────────────────────────────────────────────
    lint_result       : Optional[Any]   # SandboxResult from lint_node
    lint_passed       : bool            # shortcut: lint_result.passed
    patch             : Optional[str]   # patch generated by refactor_node
    validation_result : Optional[Any]   # SandboxResult from validator_node

    # ── Final output (set by verdict_node) ───────────────────────────────
    verdict : Optional[str]  # "APPROVE" or "REQUEST_CHANGES"
    summary : Optional[str]  # full markdown comment to post to GitHub


def build_initial_state(owner: str, repo: str, pr_number: int) -> ReviewState:
    """
    Construct a fresh ReviewState for a new review run.

    Every key is initialised to a safe default so nodes can access
    any field without checking for its existence.

    P2 fields default to None / False — this means P1 tests that do
    not exercise sandbox nodes continue to pass without changes.

    Args:
        owner:     GitHub repo owner login
        repo:      GitHub repo name
        pr_number: Pull request number

    Returns:
        Fully initialised ReviewState ready for graph.invoke()
    """
    return ReviewState(
        # ── Identity ──────────────────────────────────────────────────
        owner      = owner,
        repo       = repo,
        pr_number  = pr_number,
        thread_id  = f"{owner}-{repo}-{pr_number}",

        # ── GitHub data ───────────────────────────────────────────────
        metadata   = {},
        files      = [],
        diff       = "",

        # ── Review findings ───────────────────────────────────────────
        issues       = [],
        suggestions  = [],
        repo_context = "",

        # ── Loop control ─────────────────────────────────────────────
        reflection_count = 0,

        # ── P2: Sandbox ───────────────────────────────────────────────
        lint_result       = None,
        lint_passed       = False,
        patch             = None,
        validation_result = None,

        # ── Final output ──────────────────────────────────────────────
        verdict = None,
        summary = None,
    )